filter:
    paths:
        - 'src/*'
build:
    tests:
        override:
            -
                command: phpunit --coverage-clover=my-coverage-file
                coverage:
                    file: my-coverage-file
                    format: php-clover
tools:
    php_cpd:
        enabled: true
        excluded_dirs: {  }
        names:
            - '*.php'
        min_lines: 5
        min_tokens: 70
        filter:
            paths:
                - 'src/*'
    php_pdepend:
        excluded_dirs:
            - vendor
        enabled: true
        configuration_file: null
        suffixes:
            - php
        filter:
            paths:
                - 'src/*'
    php_changetracking:
        enabled: true
        bug_patterns:
            - '\bfix(?:es|ed)?\b'
        feature_patterns:
            - '\badd(?:s|ed)?\b'
            - '\bimplement(?:s|ed)?\b'
        filter:
            paths:
                - 'src/*'
    external_code_coverage:
        timeout: 300
        runs: 1
