name: test

on: ['push']

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        php-versions: [ '7.0', '7.1', '7.2', '7.3', '7.4' ]

    steps:
      - uses: actions/checkout@v1
      - name: Run composer install
        run: |
          composer install
      - name: phpunit
        run: |
          composer test